<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stationplan" nsURI="http://mdse.org/gt/stationplan" nsPrefix="stationplan">
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationPlan" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainStations" upperBound="-1"
        eType="#//TrainStation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainStation" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" upperBound="-1"
        eType="#//Connection" containment="true" eOpposite="#//Connection/sourceStation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/targetStation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distanceInMeters" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetStation" lowerBound="1"
        eType="#//TrainStation" eOpposite="#//TrainStation/incomingConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceStation" lowerBound="1"
        eType="#//TrainStation" eOpposite="#//TrainStation/outgoingConnections"/>
  </eClassifiers>
</ecore:EPackage>
