/*
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mdse.pts.schedule.dsl.parser.antlr.internal.InternalScheduleParser;
import org.mdse.pts.schedule.dsl.services.ScheduleGrammarAccess;

public class ScheduleParser extends AbstractAntlrParser {

	@Inject
	private ScheduleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalScheduleParser createParser(XtextTokenStream stream) {
		return new InternalScheduleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Schedule";
	}

	public ScheduleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScheduleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
