<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://mdse.org/pts/schedule" nsPrefix="schedule">
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainschedules" upperBound="-1"
        eType="#//TrainSchedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depots" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Depot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="train" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Train"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" lowerBound="1"
        upperBound="-1" eType="#//Frequency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stop" upperBound="-1" eType="#//Stop"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stop" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViaStop" eSuperTypes="#//Stop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Leg" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Leg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationStop" eSuperTypes="#//Stop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Station" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Platform" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShouldTurnAround" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DepartureTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frequency" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleDayFrequency" eSuperTypes="#//Frequency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="departuretimes" lowerBound="1"
        upperBound="-1" eType="#//DepartureTime" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departureday" lowerBound="1"
        eType="#//DepartureDay" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleDaysFrequency" eSuperTypes="#//Frequency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="departuretime" lowerBound="1"
        eType="#//DepartureTime" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departuredays" lowerBound="1"
        upperBound="7" eType="#//DepartureDay" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDay">
    <eLiterals name="MONDAY"/>
    <eLiterals name="TUESDAY" value="1"/>
    <eLiterals name="WEDNESDAY" value="2"/>
    <eLiterals name="THURSDAY" value="3"/>
    <eLiterals name="FRIDAY" value="4"/>
    <eLiterals name="SATURDAY" value="5"/>
    <eLiterals name="SUNDAY" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DepartureDay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekday" lowerBound="1"
        eType="#//WeekDay"/>
  </eClassifiers>
</ecore:EPackage>
