<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://mdse.org/pts/schedule" nsPrefix="schedule">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="depot" value="platform:/resource/org.mdse.pts.depot/model/Depot.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="network_0" value="platform:/resource/org.mdse.pts.network/model/Network.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainschedules" upperBound="-1"
        eType="#//TrainSchedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depots" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Depot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="train" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Train"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="#//Route"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" lowerBound="1"
        upperBound="-1" eType="#//Frequency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stop" upperBound="-1" eType="#//Stop"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Station" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Platform" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShouldTurnAround" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="via" eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Leg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frequency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="day" lowerBound="1" upperBound="-1"
        eType="#//DepartureDay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../org.mdse.pts.common/model/Common.ecore#//Time"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DepartureDay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekday" lowerBound="1"
        eType="ecore:EEnum ../../org.mdse.pts.common/model/Common.ecore#//WeekDay"/>
  </eClassifiers>
</ecore:EPackage>
