/*
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ScheduleUiModule extends AbstractScheduleUiModule {

	public ScheduleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
