/*
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ScheduleStandaloneSetup extends ScheduleStandaloneSetupGenerated {

	public static void doSetup() {
		new ScheduleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
