/*
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl;

import org.eclipse.xtext.generator.IGenerator2;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.mdse.pts.schedule.dsl.linking.ScheduleLinkingService;
import org.mdse.pts.schedule.dsl.scoping.ScheduleScopeProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScheduleRuntimeModule extends AbstractScheduleRuntimeModule {
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return ScheduleLinkingService.class;
	}
	
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return ScheduleScopeProvider.class;
	}
	
	@Override
	public void configureSerializerIScopeProvider(Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).annotatedWith(org.eclipse.xtext.serializer.tokens.SerializerScopeProviderBinding.class).to(ScheduleScopeProvider.class);
	}
}
