/*
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mdse.pts.schedule.dsl.ScheduleRuntimeModule;
import org.mdse.pts.schedule.dsl.ScheduleStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ScheduleIdeSetup extends ScheduleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ScheduleRuntimeModule(), new ScheduleIdeModule()));
	}
	
}
