/*
 * generated by Xtext 2.20.0
 */
package org.mdse.pts.schedule.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class ScheduleIdeModule extends AbstractScheduleIdeModule {
}
